### ISSUE TITLE
Warnings when compiling JSON.h with VS2019 (c++17)

### ISSUE THREAD

**Issue by Anton-V-K** [nwrkbiz/Cpp-SupportLibrary#4]
There are several warnings in `JSON.h` when compiling it (alone) with VS2019 (c++17):
```
3>...\JSON.h(907,40): warning C4244: 'return': conversion from 'const __int64' to 'double', possible loss of data
3>...\JSON.h(915,60): warning C4101: 'e': unreferenced local variable
3>...\JSON.h(918,56): warning C4101: 'e': unreferenced local variable
3>...\JSON.h(954,40): warning C4244: 'return': conversion from 'const double' to '__int64', possible loss of data
```
Ideally there should be no warnings at all during compilation - the project using the library may be set up with the option like 'Treat warnings as errors'

**Comment by nwrkbiz** [comment]
Thanks for the report I will look into this.

**Comment by nwrkbiz** [comment]
Should be fixed on the master branch.
